###
POST http://localhost:250/api/v1/users/resend_activation_email
Content-Type: application/json

{
  "email": "juan@api.com"
}

###

POST http://localhost:250/api/v1/users/register
Content-Type: application/json

{
  "name": "Juan",
  "email": "juan@api.com",
  "password": "123456"
}