###
POST http://localhost:250/api/v1/users/register
Content-Type: application/json

{
  "name": "Juan4",
  "email": "juan4@api.com",
  "password": "123456"
}

###
POST http://localhost:250/api/v1/users/resend_activation_email
Content-Type: application/json

{
  "email": "juan@api.com"
}

###

PUT http://localhost:250/api/v1/users/4612abc9-5168-4f31-94bb-d2e0e5e9989b/activate
Content-Type: application/json

{
"token": "4da0f72270f43d2c09d6822528417d333f28446f"
}

###

POST http://localhost:250/api/v1/users/login_check
Content-Type: application/json

{
  "username": "juan@api.com",
  "password": "passwordnew"
}

###

POST http://localhost:250/api/v1/users/request_reset_password
Content-Type: application/json

{
  "email": "juan@api.com"
}

###

POST http://localhost:250/api/v1/users/reset_password
Content-Type: application/json

{

  "userId": "4612abc9-5168-4f31-94bb-d2e0e5e9989b",
  "resetPasswordToken": "0aaa51928a2ed553cba4af47f0ecbe60780dfd74",
  "password": "password"

}

###

PUT http://localhost:250/api/v1/users/change_password
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDQ5MDY2MTIsImV4cCI6MTYxMDA5MDYxMiwidXNlcm5hbWUiOiJqdWFuQGFwaS5jb20iLCJpZCI6IjQ2MTJhYmM5LTUxNjgtNGYzMS05NGJiLWQyZTBlNWU5OTg5YiJ9.V9kDAfXRm3iwOgHIaNcsSFW46Hc6sry74NA0X8JSIE29Nu5387vvNYmwu0Cx6_vGgwG57Pcv8sJxG2Ik_7uyMAlU4TMDrLaz6mebY4NvakRl7Bpr1xF3u_vFLz7AJ_FPo9W8vpYgcDAGZvbA3F9yWAU6_7_1VzCw_QNU6lieOj885n7tJwJQ6kipRG7Ja03-9lez3V6f8zLZ4fBG3PXXQejIgLHtIt2pBZ8q18wvbi4Y_dOSqifNx4kOLkYFYxGzCyj7jJRVelmhockT_ojVeEXyH5rP7tzy6fOwGAXwVcsF4ch78Q8Y_qbaGjnOvERwTVxG1n-Eqj4j2FDZ2vypzM9Xq8uWsezSKhrxn5IJYDrV5xHsqeC5xOBaojG47_bl65eVus2AtOgKUUbwGhDOywFLYzofHhIaVkQw1fM_FSwEnO30uiAvv37B7UtCsxJbjFpj0FLDolmo4iPo3yeWTQRwZ5OVx8Xd3qVpuInupoEyuuEQFIdbIQ7fFAaBSPXFcE-e4H8R8VN_gDFbqa5gtzhgtU5oBzw3U8p69R-tkv29zCkgSjumNby1P6uDmQg8C8JTv-qXISKP89Hm3ioKYDPE2MlduQHqyoeAPLSld44NMMEe-HENEFgShZ6giarvWqz_CZ3tVMQ1g2lBsf4TLzsvfOb8YrxJjA-G7PSSO-A

{

  "oldPassword": "password",
  "newPassword": "passwordnew"

}





###

POST http://localhost:250/api/v1/users/login_check
Content-Type: application/json

{
  "username": "peter@api.com",
  "password": "password"
}

###
###

POST http://localhost:250/api/v1/users/4eb944f1-ff68-4f45-b882-2babcd1f88a0/avatar
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDUwNzk5MTEsImV4cCI6MTYxMDI2MzkxMSwidXNlcm5hbWUiOiJwZXRlckBhcGkuY29tIiwiaWQiOiI0ZWI5NDRmMS1mZjY4LTRmNDUtYjg4Mi0yYmFiY2QxZjg4YTAifQ.OS8sbHwsdxXmgOQ8T1ZkwLn86xaK4GtXa4pYguds4xENpeFDohrOPWd9kAp_01x-d2_Dmq3c4_x7R8YkYZA_Zx3HYIzRaU8Lw2ir9zq3ILdyhgVj0Dpy68njcLeXcjwoA5UqdLTq6fYudHcvscU2ngfboCRlvtEhr8awNslf_XYipEljA6sXapKVjGCnwhD3P3G1XlRizKHKJKw8r1i1Xdgv6nLQAvix98qu1Cqb_pvYjGZ-pGjZ7QzM3emvRwxqghnf00dcHC026G4IhN0gpbEJhbw_fAwqetN5faBwzTKPFHQLEYnEDJi3TkfL6UXM-79gCGZwoL8OZxYej4lUch81VerpbcGryzWhk3fJYZSot3f6yQJdE6e938D0DBaG5JaoKX4kD7AyjC57jrU93ONcq9R04bbPQ0peFAeD_cqc2oC1Ulgq2RxwmrUuOoxLLVTVUI_qwA5bwhgZnbDlqXUph0eXJoFM_aPKpUyLKbSc3_oh4m024gEle7NWf6ofPYw02oKgA8x05cijmik5hOdpjGj9w8TjbCa_WuQ-VNCHjH_o-7amIDYzOeQ2PMlU3tzB6rF_WRSj4Z6YRFG4EoZwV0aJgZM0C_yxuFaQI2p1fEpWrQ1yPP51PAJ-pWFl6PuQRt6msBbVZ6BY3IYqxk01koO3cxCN8JdD1ojqdhk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="avatar"; filename="avatar.png"

< /home/sergio/Escritorio/lisbon.png

###

PUT http://localhost:250/api/v1/groups/f06dc43c-923a-4f8f-a3a0-ee0bbab3b626/send_request
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDUwNzk5MTEsImV4cCI6MTYxMDI2MzkxMSwidXNlcm5hbWUiOiJwZXRlckBhcGkuY29tIiwiaWQiOiI0ZWI5NDRmMS1mZjY4LTRmNDUtYjg4Mi0yYmFiY2QxZjg4YTAifQ.OS8sbHwsdxXmgOQ8T1ZkwLn86xaK4GtXa4pYguds4xENpeFDohrOPWd9kAp_01x-d2_Dmq3c4_x7R8YkYZA_Zx3HYIzRaU8Lw2ir9zq3ILdyhgVj0Dpy68njcLeXcjwoA5UqdLTq6fYudHcvscU2ngfboCRlvtEhr8awNslf_XYipEljA6sXapKVjGCnwhD3P3G1XlRizKHKJKw8r1i1Xdgv6nLQAvix98qu1Cqb_pvYjGZ-pGjZ7QzM3emvRwxqghnf00dcHC026G4IhN0gpbEJhbw_fAwqetN5faBwzTKPFHQLEYnEDJi3TkfL6UXM-79gCGZwoL8OZxYej4lUch81VerpbcGryzWhk3fJYZSot3f6yQJdE6e938D0DBaG5JaoKX4kD7AyjC57jrU93ONcq9R04bbPQ0peFAeD_cqc2oC1Ulgq2RxwmrUuOoxLLVTVUI_qwA5bwhgZnbDlqXUph0eXJoFM_aPKpUyLKbSc3_oh4m024gEle7NWf6ofPYw02oKgA8x05cijmik5hOdpjGj9w8TjbCa_WuQ-VNCHjH_o-7amIDYzOeQ2PMlU3tzB6rF_WRSj4Z6YRFG4EoZwV0aJgZM0C_yxuFaQI2p1fEpWrQ1yPP51PAJ-pWFl6PuQRt6msBbVZ6BY3IYqxk01koO3cxCN8JdD1ojqdhk

{

"email": "roger@api.com"

}

###

PUT http://localhost:250/api/v1/groups/f06dc43c-923a-4f8f-a3a0-ee0bbab3b626/accept_request
Content-Type: application/json

{

  "userId": "1e341e0f-116a-4fee-ba25-72cfd1d0a812",
  "token": "b0e66fb10ce85c8b44519f211e7dbb421c51252b"

}

###

POST http://localhost:250/api/v1/movements/5ef68222-f696-4f23-a4fa-bf088678b975/upload_file
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDUwNzk5MTEsImV4cCI6MTYxMDI2MzkxMSwidXNlcm5hbWUiOiJwZXRlckBhcGkuY29tIiwiaWQiOiI0ZWI5NDRmMS1mZjY4LTRmNDUtYjg4Mi0yYmFiY2QxZjg4YTAifQ.OS8sbHwsdxXmgOQ8T1ZkwLn86xaK4GtXa4pYguds4xENpeFDohrOPWd9kAp_01x-d2_Dmq3c4_x7R8YkYZA_Zx3HYIzRaU8Lw2ir9zq3ILdyhgVj0Dpy68njcLeXcjwoA5UqdLTq6fYudHcvscU2ngfboCRlvtEhr8awNslf_XYipEljA6sXapKVjGCnwhD3P3G1XlRizKHKJKw8r1i1Xdgv6nLQAvix98qu1Cqb_pvYjGZ-pGjZ7QzM3emvRwxqghnf00dcHC026G4IhN0gpbEJhbw_fAwqetN5faBwzTKPFHQLEYnEDJi3TkfL6UXM-79gCGZwoL8OZxYej4lUch81VerpbcGryzWhk3fJYZSot3f6yQJdE6e938D0DBaG5JaoKX4kD7AyjC57jrU93ONcq9R04bbPQ0peFAeD_cqc2oC1Ulgq2RxwmrUuOoxLLVTVUI_qwA5bwhgZnbDlqXUph0eXJoFM_aPKpUyLKbSc3_oh4m024gEle7NWf6ofPYw02oKgA8x05cijmik5hOdpjGj9w8TjbCa_WuQ-VNCHjH_o-7amIDYzOeQ2PMlU3tzB6rF_WRSj4Z6YRFG4EoZwV0aJgZM0C_yxuFaQI2p1fEpWrQ1yPP51PAJ-pWFl6PuQRt6msBbVZ6BY3IYqxk01koO3cxCN8JdD1ojqdhk
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="file.png"

< /home/sergio/Escritorio/ticket.png

###

POST http://localhost:250/api/v1/movements/5ef68222-f696-4f23-a4fa-bf088678b975/download_file
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2MDUwNzk5MTEsImV4cCI6MTYxMDI2MzkxMSwidXNlcm5hbWUiOiJwZXRlckBhcGkuY29tIiwiaWQiOiI0ZWI5NDRmMS1mZjY4LTRmNDUtYjg4Mi0yYmFiY2QxZjg4YTAifQ.OS8sbHwsdxXmgOQ8T1ZkwLn86xaK4GtXa4pYguds4xENpeFDohrOPWd9kAp_01x-d2_Dmq3c4_x7R8YkYZA_Zx3HYIzRaU8Lw2ir9zq3ILdyhgVj0Dpy68njcLeXcjwoA5UqdLTq6fYudHcvscU2ngfboCRlvtEhr8awNslf_XYipEljA6sXapKVjGCnwhD3P3G1XlRizKHKJKw8r1i1Xdgv6nLQAvix98qu1Cqb_pvYjGZ-pGjZ7QzM3emvRwxqghnf00dcHC026G4IhN0gpbEJhbw_fAwqetN5faBwzTKPFHQLEYnEDJi3TkfL6UXM-79gCGZwoL8OZxYej4lUch81VerpbcGryzWhk3fJYZSot3f6yQJdE6e938D0DBaG5JaoKX4kD7AyjC57jrU93ONcq9R04bbPQ0peFAeD_cqc2oC1Ulgq2RxwmrUuOoxLLVTVUI_qwA5bwhgZnbDlqXUph0eXJoFM_aPKpUyLKbSc3_oh4m024gEle7NWf6ofPYw02oKgA8x05cijmik5hOdpjGj9w8TjbCa_WuQ-VNCHjH_o-7amIDYzOeQ2PMlU3tzB6rF_WRSj4Z6YRFG4EoZwV0aJgZM0C_yxuFaQI2p1fEpWrQ1yPP51PAJ-pWFl6PuQRt6msBbVZ6BY3IYqxk01koO3cxCN8JdD1ojqdhk
Content-Type: application/json

{

  "filePath": "file/273c093e7d2b57f6f885253f68b937a7638a91c4.png"

}